### ISSUE TITLE
Draw Line

### ISSUE THREAD

**Issue by alexapostolu** [CSC207-2023Y-UofT/course-project-aardvark#36]
Create a function that draws a line.

Parameters: (mouse_start_x, mouse_start_y, mouse_end_x, mouse_end, y)

![Image](https://github.com/CSC207-2023Y-UofT/course-project-aardvark/assets/55321722/7c7415cd-28cb-44be-94a3-f792d6395803)

**Comment by latxh** [comment]
Deprioritized
